# Tensor
- A tensor is a generalization of scalars, vectors, and matrices. It can be thought of as a multi-dimensional array.
- Tensors are fundamental building blocks in PyTorch and are used for various mathematical operations.
- Scalar: A 0-dimensional tensor (e.g., a single number).
    - Vector: A 1-dimensional tensor (e.g., an array of numbers).
    - Matrix: A 2-dimensional tensor (e.g., a table of numbers).
    - Higher-Dimensional Tensors: Tensors with three or more dimensions (e.g., a 3D array for images).    

# PyTorch Tensors vs. NumPy Arrays

- Creation: PyTorch tensors can be created directly from NumPy arrays and vice versa.
- GPU Acceleration: PyTorch tensors can leverage GPU for computations, while NumPy operates on the CPU.
- Autograd: Tensors in PyTorch support automatic differentiation, which is essential for training neural networks.


In [1]:
import torch

# Define tensor

## 1. Define a tensor using list/numpy array

In [2]:
# 1. Define a tensor using list/numpy array

tensor_1d = torch.tensor([1,2,3])
tensor_2d = torch.tensor([[4,5,6], [7,8,9]])

print(tensor_1d)
print(tensor_2d)




tensor([1, 2, 3])
tensor([[4, 5, 6],
        [7, 8, 9]])


## Define a 1D tensor using arange

In [3]:
# Define a 1D tensor using arange
range_tensor = torch.arange(0,10, step=2)  # Returns a 1D tensor
range_tensor

tensor([0, 2, 4, 6, 8])

# Built-in Functions
- torch.zeros - Creates 0 values tensor of given shape
- torch.ones -  Creates 1 values tensor of given shape
- torch.zeros_like - Returns a tensor filled with the scalar value 0, with the same size as input
- torch.ones_like - Returns a tensor filled with the scalar value 0, with the same size as input
- torch.rand - Gnenerate tensor of given shape with radom values.

In [4]:
# 1.
all_zeros = torch.zeros(3,3)  
all_zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [5]:
# 2.
all_ones = torch.ones(3,3)
all_ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [6]:
# 3.
torch.zeros_like(all_ones)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# 4.
torch.rand(3,3)

tensor([[0.1155, 0.8071, 0.7741],
        [0.3254, 0.2945, 0.7524],
        [0.2311, 0.9483, 0.1454]])

**Difference between zeros(), zeros_like(), and zero_**
| Feature         | `torch.zeros()`                              | `torch.zeros_like()`                             | `.zero_()`                          |
|------------------|---------------------------------------------|-------------------------------------------------|-------------------------------------|
| **Purpose**      | Creates a tensor filled with zeros           | Creates a tensor filled with zeros, same shape and dtype as the input tensor | Fills an existing tensor with zeros (in-place) |
| **New Tensor?**  | Yes                                         | Yes                                             | No (modifies the original tensor)   |
| **Arguments**    | Shape, dtype, device, etc.                  | A reference tensor                              | None (called on the tensor)         |
| **Use Case**     | Create a new zero tensor                    | Create a new zero tensor with same properties as another tensor | Reset values of an existing tensor to zeros |
| **In-place?**    | No                                          | No                                              | Yes                                 |


In [8]:
a = torch.zeros(4,8)
a

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
b = torch.ones(3,4)  # Creates a new tensor based on given shape
b


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
c = torch.zeros_like(b)  # Creates new tensor based on reference tensor
c

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [11]:
d = b.zero_()  # In place replacement
d

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

# Basic Tensor Operations

## 1. Reshape a tensor
- a_new = a.view([dim])

In [12]:
a = torch.tensor([1,2,3])
a_new = a.view([3,1])

In [13]:
a.shape

torch.Size([3])

In [11]:
a_new.shape

torch.Size([3, 1])

In [17]:
a_new

tensor([[1],
        [2],
        [3]])

In [18]:
a_new.shape

torch.Size([3, 1])

In [21]:
a_new1= a_new.view(-1)
a_new1

tensor([1, 2, 3])

In [22]:
a_new1.shape

torch.Size([3])

In [26]:
x = torch.arange(0,60)
x1 = x.view(3,4,5)
x1.shape

torch.Size([3, 4, 5])

In [28]:
x2 = x1.view(-1)
x2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59])

In [29]:
x2.shape

torch.Size([60])

In [31]:
x3 = x2.view(12,-1)
x3.shape

torch.Size([12, 5])

**Difference between view() and reshape():**

### Difference Between `view()` and `reshape()` in PyTorch

| **Feature**       | **`view()`**                | **`reshape()`**                   |
|--------------------|-----------------------------|------------------------------------|
| **Memory Layout**  | Requires contiguous data   | Works with non-contiguous data    |
| **Data Copying**   | Never copies data          | Copies data if needed             |
| **Error Handling** | Throws error if non-contiguous | Handles non-contiguous tensors |
| **Performance**    | Faster                     | Slightly slower (if copying needed) |

- If sure that data is contiguous, go with view(), it takes less run time.
- If not sure about changed data is contigous or not, go with reshape().

In [14]:
# Example
a = torch.arange(12).view(3,4)
a

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [18]:
a.t().view(6,2)  # Error because transpose make tensor non-contiguous


RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [20]:
a.t().reshape(6,2)  # Works with reshape()

tensor([[ 0,  4],
        [ 8,  1],
        [ 5,  9],
        [ 2,  6],
        [10,  3],
        [ 7, 11]])

## 2. Access elements using index

In [12]:
b = torch.empty(3,3)
b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

**We can define a tensor using torch.empty(). It is not a zero tensor but it initializes the tensor of given shape with garbage values. The zeros are coincidental.**

In [35]:
# Indexing
b[0][1] = 1
b[1][2] = 9
b[0][2] = 5

In [14]:
b

tensor([[0., 1., 5.],
        [0., 0., 9.],
        [0., 0., 0.]])

In [15]:
b[0][1]

tensor(1.)

## Slicing

- a[:,:]

In [16]:
b[:, 0]  # First col

tensor([0., 0., 0.])

In [61]:
b[0,:] # First row

tensor([0., 1., 5.])

In [63]:
b[0:2, 1:]

tensor([[1., 5.],
        [0., 9.]])

# Mathematical Operations

In [17]:
import random

random.seed(42)
a1 = torch.arange(9,0, step=-1)
a1 = a1.view(3,3)
a1

tensor([[9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]])

In [18]:
a2 = torch.arange(1,10, step=1)
a2 = a2.view(3,3)
a2

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## 1. Element wise operations

### a_add = a1+a2

In [19]:
# Addition
a_add = a1+a2
a_add

tensor([[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]])

### a_mul = a1*a2

In [85]:
# Multiplication
a_mul = a1*a2
a_mul

tensor([[ 9, 16, 21],
        [24, 25, 24],
        [21, 16,  9]])

### a_div = a1/a2

In [87]:
# Division
a_div = a1/a2
a_div

tensor([[9.0000, 4.0000, 2.3333],
        [1.5000, 1.0000, 0.6667],
        [0.4286, 0.2500, 0.1111]])

### a_pow = a1**2

In [90]:
# Power
a_pow = a1**2
a_pow

tensor([[81, 64, 49],
        [36, 25, 16],
        [ 9,  4,  1]])

## 2. Reduction operators/ Aggregators

In [130]:
a1, a2

(tensor([[9, 8, 7],
         [6, 5, 4],
         [3, 2, 1]]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

### a1.sum(dim=?)

In [93]:
# 1. Sum
a1.sum()  # Sum of all elements

tensor(45)

In [97]:
a1.sum(dim=1)  # Sum of elements of dimension 1

tensor([24, 15,  6])

- mean() aggregator can only be applied on floating type or complex type tensors.
- **It cannot work with tensor defined as int type beacuse the output of mean can be fractional.**

### a1.mean(dim=?)

In [104]:
# 2. Mean

a1.mean(dim=0)  # Runtime error due to int type tensor

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [106]:
# Conver tensor to float type

a1.float().mean()

tensor(5.)

In [110]:
a1

tensor([[9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]])

In [109]:
a1.float().mean(dim=1)

tensor([8., 5., 2.])

### max_value, max_index = a1.max(dim =?)

In [122]:
# 3. Max

max_value, max_index = a1.max(dim =1)
max_value

tensor([9, 6, 3])

In [123]:
max_index

tensor([0, 0, 0])

In [20]:
a1.max()

tensor(9)

- If you call tensor.max() without specifying a dimension, it will only give you the maximum value.
- If you call tensor.max(dim=...), it will return both the maximum values along the specified dimension and their indices, allowing you to know where those maximum values are located within the tensor.
- Same with min values.

### a1.min(dim=0)

In [125]:
a1.min()

tensor(1)

In [126]:
a1.min(dim=0)

torch.return_types.min(
values=tensor([3, 2, 1]),
indices=tensor([2, 2, 2]))

## 3. Concat and Stacking

In [129]:
# 1. Concatenation

a1, a2

(tensor([[9, 8, 7],
         [6, 5, 4],
         [3, 2, 1]]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

### a_concat= torch.concat([a1,a2], dim=?)

In [140]:
a_concat0= torch.concat([a1,a2], dim=0)
a_concat0


tensor([[9, 8, 7],
        [6, 5, 4],
        [3, 2, 1],
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [137]:
a_concat0.shape

torch.Size([6, 3])

In [139]:
a_concat1 = torch.concat([a1,a2], dim=1)
a_concat1

tensor([[9, 8, 7, 1, 2, 3],
        [6, 5, 4, 4, 5, 6],
        [3, 2, 1, 7, 8, 9]])

In [141]:
a_concat1.shape

torch.Size([3, 6])

### a_stack = torch.stack([a1, a2], dim=?)

In [148]:
# 2. Stacking

a_stack1 = torch.stack([a1, a2])
a_stack1

tensor([[[9, 8, 7],
         [6, 5, 4],
         [3, 2, 1]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [149]:
a_stack1.shape

torch.Size([2, 3, 3])

In [150]:
a_stack2 = torch.stack([a1,a2], dim=1)
a_stack2

tensor([[[9, 8, 7],
         [1, 2, 3]],

        [[6, 5, 4],
         [4, 5, 6]],

        [[3, 2, 1],
         [7, 8, 9]]])

In [151]:
a_stack2.shape

torch.Size([3, 2, 3])

## 4. Transpose and Permute

In [152]:
a1

tensor([[9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]])

### a1.T

In [22]:
# Transpose
a1.T  # Swap dimensions

tensor([[9, 6, 3],
        [8, 5, 2],
        [7, 4, 1]])

### a1.permute(new order)

- In this we will give the order of new dimension. The order is given in the form of index of the original dimensions.

e.g. 
a.size = [2,3,4,5]

We want to change it to [4,3,5,2], then we will give = a.permute([2,1,3,0]).

2,1,3,0 are the indices of original dimensions in size.



In [28]:
a1 = torch.arange(1,25)
a1 = a1.view(2,3,4)
a1

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

In [29]:
a1.shape

torch.Size([2, 3, 4])

In [30]:
a2 = a1.permute(2,0,1)  # Change shape to 4,2,3

In [31]:
a2.shape

torch.Size([4, 2, 3])

When to Use permute
- Data Preparation: Often used when preparing data for models, especially in deep learning where input dimensions must match expected shapes (e.g., switching between channel-first and channel-last formats).
- Aligning Dimensions: Useful when you need to align tensor dimensions for operations like matrix multiplication, broadcasting, or concatenation.

# In-place Operations


## tensor.add_(1)  





In [39]:
a1 = torch.arange(0,20)
a1 = a1.view(5,2,2)
a1

tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]]])

In [40]:
a1.add_(1)  # Adds 1 to all elements in place

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]],

        [[17, 18],
         [19, 20]]])

## tensor.mul_(2) 

In [42]:
a1.mul_(2)

tensor([[[ 2,  4],
         [ 6,  8]],

        [[10, 12],
         [14, 16]],

        [[18, 20],
         [22, 24]],

        [[26, 28],
         [30, 32]],

        [[34, 36],
         [38, 40]]])

- add_() and add()
- mul_() and mul() have diferences how? 
- add_ and mul_ perform inplace opertaions on tensors while other ones do not modify the original tensors.

# Boolean Operations

## a_bool = a > 2  
 

In [62]:
a = torch.tensor([1,2,3,4,5,6,3,2,4,1,5,7,1,2])
bool_tensor = a>3   # Comparison
bool_tensor

tensor([False, False, False,  True,  True,  True, False, False,  True, False,
         True,  True, False, False])

## a[a_bool] 



In [63]:
a[a>4]  # Filtering

tensor([5, 6, 5, 7])

# Other Useful Operations
## tensor.clone() 

In [64]:
b = a.clone()  # Create copy
b

tensor([1, 2, 3, 4, 5, 6, 3, 2, 4, 1, 5, 7, 1, 2])

## a.resize_as_(b)

In [68]:
a.size()

torch.Size([14])

In [69]:
b = b.view(2,7)
b.size()

torch.Size([2, 7])

In [72]:
# Make a of size b
a = a.resize_as_(b)
a.size()

torch.Size([2, 7])

## torch.eq

In [35]:
x1 = torch.arange(0,10).view(5,-1)
x1


tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [37]:
x2 = torch.Tensor([[0, 1],
        [3, 3],
        [4, 5],
        [4, 7],
        [8, 9]])
x2

tensor([[0., 1.],
        [3., 3.],
        [4., 5.],
        [4., 7.],
        [8., 9.]])

In [42]:
torch.eq(x1, x2)

tensor([[ True,  True],
        [False,  True],
        [ True,  True],
        [False,  True],
        [ True,  True]])

In [43]:
torch.eq(x1, x2).view(-1)

tensor([ True,  True, False,  True,  True,  True, False,  True,  True,  True])