Numerical Python (NumPy)

- No matter what the data are, the first step in making them analyzable will be to transform them into arrays of numbers.

- In some ways, NumPy arrays are like Python’s built-in list type, but NumPy arrays provide much more efficient storage and data operations as the arrays grow larger in size. NumPy arrays form the core of nearly the entire ecosystem of data science tools in Python.

- backbone of many other scientific libraries, such as SciPy, Pandas, and TensorFlow.

Why is NumPy efficient?

- Memory Efficiency: NumPy arrays are more compact than Python lists, using less memory for the same data.

- Speed: Operations on NumPy arrays are much faster than equivalent operations on Python lists due to optimized C and Fortran code running behind the scenes.

- Convenience: NumPy provides many functions to perform common mathematical operations on arrays, making it easier to manipulate and process large datasets.


In [23]:
# Version check 
import numpy as np
np.__version__

'2.0.1'






3. Slicing of arrays
- Getting and setting smaller subarrays within a larger array

4. Reshaping of arrays
- Changing the shape of a given array

5. Joining and splitting of arrays
- Combining multiple arrays into one, and splitting one array into many

# 1. Attributes of arrays
- Determining the size, shape, memory consumption, and data types of arrays.

In [24]:
# Generate a random array

import numpy as np
np.random.seed(0)   # Seed numpy random number generator to ensure,
                    # same random numbers are generated every time this code runs.

x1= np.random.randint(10, size=6)   # One dimensional array of length 6
print(f"{x1=}")

x2= np.random.randint(10, size=(3,4))  # Two dimensional array 
print(f"{x2=}")

x3= np.random.randint(10, size=(3,4,5))  # Three dimensional array
print(f"{x3=}")


x1=array([5, 0, 3, 3, 7, 9])
x2=array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])
x3=array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])


In [25]:
# .ndim gives number of dimensions

print(f"{x1.ndim=}, {x2.ndim=}, {x3.ndim=}")


x1.ndim=1, x2.ndim=2, x3.ndim=3


In [26]:
# .shape gives shape array
print(f"{x1.shape=}, {x2.shape=}, {x3.shape=}")

x1.shape=(6,), x2.shape=(3, 4), x3.shape=(3, 4, 5)


In [27]:
# .size gives total number of elements
print(f"{x1.size=}, {x2.size=}, {x3.size=}")

x1.size=6, x2.size=12, x3.size=60


In [28]:
# .dtype gives data type of an array
print(f"{x1.dtype=}")

x1.dtype=dtype('int64')


In [29]:
# .itemsize, which lists the size (in bytes) of each array element,
print(f"{x3.itemsize=}")  # each element size is 8 bytes

x3.itemsize=8


In [30]:
#  .nbytes, which lists the total size (in bytes) of the array:
print(f"{x1.nbytes=}")  # 6 elements x 8 bytes = 48 bytes

x1.nbytes=48


# 2. Indexing of arrays
- Getting and setting the value of individual array elements.

## One dimensional array

In [34]:
print(x1)

[5 0 3 3 7 9]


## Two dimensional array

In [39]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [41]:
print(x2[0,0])

3


In [42]:
print(x2[-1,-3])

6


In [36]:
print(x1[-3])

3


## Modify array values
- Keep in mind that, unlike Python lists, NumPy arrays have a fixed type. 
- This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. Don’t be caught unaware by this behavior!

In [43]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [45]:
x2[0,0] = 12  # Modify [0,0] value
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [46]:
x2[0,0] = 5.1234  # Try replcing it with float value


In [48]:
x2  # See the truncated float to int 5

array([[5, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

# Array Slicing: Accessing Subarrays